title: CSCI 264 — Assembly Language
description: Lecture notes, Fall 2026
baseurl: "/csci264"
theme: minima
markdown: kramdown
future: true
collections:
  lectures:
    output: true
    permalink: /lectures/:name/
defaults:
  - scope:
      path: ""
      type: lectures
    values:
      layout: page